export const GET_RECORD = 'GET_RECORD';
export const DELETE_RECORD = 'DELETE_RECORD';
export const ADD_RECORD = 'ADD_RECORD';
export const UPDATE_RECORD = 'UPDATE_RECORD';
export const GET_SINGLE_RECORD = 'GET_SINGLE_RECORD';
